namespace AiBot.Core;

public static class TrainingDataset
{
    public static IReadOnlyList<TrainingExample> Examples { get; } =
    [
        new(IntentType.Greeting, "привіт допоможи спланувати подорож"),
        new(IntentType.Greeting, "добрий день потрібна консультація з туризму"),
        new(IntentType.Greeting, "вітаю підкажи куди поїхати"),
        new(IntentType.Greeting, "здрастуй хочу підібрати тур"),
        new(IntentType.Greeting, "привіт туристичний консультанте"),
        new(IntentType.Greeting, "добрий вечір планую відпустку"),
        new(IntentType.Greeting, "хей допоможи з поїздкою"),
        new(IntentType.Greeting, "можеш бути моїм travel advisor"),
        new(IntentType.Greeting, "почнемо планувати маршрут"),
        new(IntentType.Greeting, "мені потрібен туристичний асистент"),
        new(IntentType.Greeting, "привіт розкажи що обрати для відпочинку"),
        new(IntentType.Greeting, "стартуємо консультацію щодо подорожі"),

        new(IntentType.DestinationAdvice, "куди поїхати на море влітку"),
        new(IntentType.DestinationAdvice, "порадь місто для першої подорожі в європу"),
        new(IntentType.DestinationAdvice, "який напрям обрати для сімейного відпочинку"),
        new(IntentType.DestinationAdvice, "хочу романтичну подорож на вихідні"),
        new(IntentType.DestinationAdvice, "підбери країну для бюджетної відпустки"),
        new(IntentType.DestinationAdvice, "де краще відпочити у вересні"),
        new(IntentType.DestinationAdvice, "порадь місце для активного туризму"),
        new(IntentType.DestinationAdvice, "який курорт підійде для дітей"),
        new(IntentType.DestinationAdvice, "хочу поїхати в гори що обрати"),
        new(IntentType.DestinationAdvice, "порівняй Прагу і Відень для подорожі"),
        new(IntentType.DestinationAdvice, "що краще Туреччина чи Греція"),
        new(IntentType.DestinationAdvice, "порадь напрям для короткої відпустки"),

        new(IntentType.ItineraryPlanning, "склади маршрут на три дні у Парижі"),
        new(IntentType.ItineraryPlanning, "що подивитися у Львові за вихідні"),
        new(IntentType.ItineraryPlanning, "план прогулянки по Риму на 2 дні"),
        new(IntentType.ItineraryPlanning, "допоможи розкласти екскурсії по днях"),
        new(IntentType.ItineraryPlanning, "зроби itinerary для Барселони"),
        new(IntentType.ItineraryPlanning, "який порядок відвідати пам'ятки"),
        new(IntentType.ItineraryPlanning, "маршрут з музеями і ресторанами"),
        new(IntentType.ItineraryPlanning, "план поїздки в Карпати на weekend"),
        new(IntentType.ItineraryPlanning, "розпиши день прибуття і день виїзду"),
        new(IntentType.ItineraryPlanning, "склади маршрут без поспіху"),
        new(IntentType.ItineraryPlanning, "що включити у туристичний план"),
        new(IntentType.ItineraryPlanning, "запропонуй маршрут центром міста"),

        new(IntentType.BudgetEstimate, "скільки грошей потрібно на подорож"),
        new(IntentType.BudgetEstimate, "розрахуй бюджет на двох у Стамбул"),
        new(IntentType.BudgetEstimate, "маю 500 євро що можна обрати"),
        new(IntentType.BudgetEstimate, "оцінка витрат на готель і харчування"),
        new(IntentType.BudgetEstimate, "який бюджет потрібен на 5 днів"),
        new(IntentType.BudgetEstimate, "порахуй приблизну вартість поїздки"),
        new(IntentType.BudgetEstimate, "як зекономити на турі"),
        new(IntentType.BudgetEstimate, "дешевий маршрут до Праги"),
        new(IntentType.BudgetEstimate, "скільки коштує weekend у Відні"),
        new(IntentType.BudgetEstimate, "підбери варіант до 20000 грн"),
        new(IntentType.BudgetEstimate, "витрати на транспорт житло квитки"),
        new(IntentType.BudgetEstimate, "бюджетний відпочинок для трьох людей"),

        new(IntentType.BookingHelp, "як забронювати готель"),
        new(IntentType.BookingHelp, "що перевірити перед бронюванням туру"),
        new(IntentType.BookingHelp, "допоможи вибрати рейс"),
        new(IntentType.BookingHelp, "як знайти житло біля центру"),
        new(IntentType.BookingHelp, "які параметри бронювання важливі"),
        new(IntentType.BookingHelp, "порадь коли купувати квитки"),
        new(IntentType.BookingHelp, "як обрати страховку для туру"),
        new(IntentType.BookingHelp, "бронювання апартаментів чи готелю"),
        new(IntentType.BookingHelp, "на що дивитися в умовах скасування"),
        new(IntentType.BookingHelp, "як перевірити рейтинг готелю"),
        new(IntentType.BookingHelp, "допоможи з бронюванням екскурсії"),
        new(IntentType.BookingHelp, "які документи потрібні при заселенні"),

        new(IntentType.TravelDocuments, "які документи потрібні для поїздки"),
        new(IntentType.TravelDocuments, "чи потрібна віза в Туреччину"),
        new(IntentType.TravelDocuments, "що взяти з собою за кордон"),
        new(IntentType.TravelDocuments, "підкажи про паспорт і страховку"),
        new(IntentType.TravelDocuments, "документи для подорожі з дитиною"),
        new(IntentType.TravelDocuments, "які правила перетину кордону"),
        new(IntentType.TravelDocuments, "що перевірити перед виїздом"),
        new(IntentType.TravelDocuments, "чи потрібен covid сертифікат"),
        new(IntentType.TravelDocuments, "перелік документів для туру"),
        new(IntentType.TravelDocuments, "чи достатньо id карти"),
        new(IntentType.TravelDocuments, "яка страховка потрібна туристу"),
        new(IntentType.TravelDocuments, "що підготувати для авіаперельоту"),

        new(IntentType.WeatherSeason, "коли найкращий сезон для Єгипту"),
        new(IntentType.WeatherSeason, "яка погода у Греції в травні"),
        new(IntentType.WeatherSeason, "чи тепло в Туреччині у жовтні"),
        new(IntentType.WeatherSeason, "коли їхати в Карпати на лижі"),
        new(IntentType.WeatherSeason, "сезон дощів у Таїланді"),
        new(IntentType.WeatherSeason, "погода в Парижі навесні"),
        new(IntentType.WeatherSeason, "що одягнути в подорож у грудні"),
        new(IntentType.WeatherSeason, "чи підходить вересень для моря"),
        new(IntentType.WeatherSeason, "коли менше туристів у Римі"),
        new(IntentType.WeatherSeason, "який місяць краще для Барселони"),
        new(IntentType.WeatherSeason, "порадь сезон для пляжного відпочинку"),
        new(IntentType.WeatherSeason, "коли дешевше і комфортніше летіти")
    ];
}
